### ISSUE TITLE
Too many requests being made to infura/alchemy

### ISSUE THREAD

**Issue by akwritescode** [opynfinance/squeeth-monorepo#11]
**Describe the bug**

to many  calls made to fetch latest block 

**To Reproduce**

1. Go to 'squeeth.com'
2.Open the network monitor
3. Look at the calls, you will see that a lot of duplicate calls are being made to infura/alchemy to fetch the latest block

**Expected behavior**
Do not make too many calls as that means the service provider will give us a 429 error sooner than later

**Screenshots**

**Additional context**

**Comment by alexisgauba** [comment]
From Koushik: "useETHprice and useTokenBalance is used in multiple places. So in a page there can be 5-6 requests every 10 seconds. We can move this to a context and use it from there. This will drastically reduce the calls. And instead of polling at time interval we can poll at new blocks"

**Comment by akwritescode** [comment]
5-6 requests in 10 seconds wouldnt be an issue in itself ( well relatively) 
we are making close to 1.5 requests per second if you stay on page for 100 + seconds
but on initial load i see 100+ calls going out in first 1-3 seconds

**Comment by akwritescode** [comment]
hey @alexisgauba re-opening this again as the issue is still not complete fixed

**Comment by 0xAlx0** [comment]
guys, let me take this issue up. I had the same problem before so i can help close this one out

**Comment by 0xAlx0** [comment]
@akwritescode new here and looking to contribute, I was asked by Anil to take up this issue. im trying to replicate the issue but where can I find the network monitor? are you referring to the browser tools?

**Comment by alexisgauba** [comment]
@0xAlx0 awesome to meet ya and thanks for jumping in! yep referring to the browser tools! You'll notice that there are lots of calls coming from useSqueethPool and useController hooks in particular. That's where we make .call() smart contract calls to get data and where most of the requests are coming from.

**Comment by akwritescode** [comment]
@0xAlx0 
Thanks for jumping on this one. This is Anil. 
If you are considering to solve this through some improved state management, please do take a look this library https://github.com/derrickbeining/react-atom 
That maybe helpful 
Thanks

**Comment by 0xAlx0** [comment]
@akwritescode will look into it this weekend!

**Comment by akwritescode** [comment]
do you have any updates @0xAlx0 ?
