### ISSUE TITLE
Short positions don't show up on the positions tab or positions card when someone separately mints and then sells directly on Uniswap

### ISSUE THREAD

**Issue by hitsuzen-eth** [opynfinance/squeeth-monorepo#15]
Short Squeeth position can not be seen due to "Division by zero".
Already tried to hard refresh, new browser and so on.

**Comment by alexisgauba** [comment]
Hey! Where are you seeing a division by 0 error? 

You're not seeing your short squeeth position on the positions tab or positions card? 

If you can, do you want to DM me a screenshot / console? @Alexis²#3549 on discord 😄

**Comment by hitsuzen-eth** [comment]
I dont use Discord.

Cant view short position on summary on "Trade" page and on "Position" page but I see that I've a position on "Trade" page "Collateral you redeem: xxx ETH " and "Current Collateral ratio: XXX %"

Division by zero when const trade = await Trade... on useSqueethPool.ts

Really annoying.

**Comment by alexisgauba** [comment]
Appreciate the feedback and sorry about this! We'll work on getting this fixed but I can't replicate rn - do you think you could email me your addr at alexis@opyn.co ?

**Comment by hitsuzen-eth** [comment]
Done

**Comment by alexisgauba** [comment]
Thank you very much! We'll look into this and keep you updated

**Comment by alexisgauba** [comment]
Ah ok it looks like you minted oSQTH and then separately sold it on Uniswap vs. using our Short/Open tab that mints and sells in one step 

This is why it’s not showing a position, because that flow isn’t currently supported 

We’ll work on adding this and I’ll you know as soon its available!

**Comment by hitsuzen-eth** [comment]
o.O 
Ok... 
Please verify your code on etherscan so we can manage our position(and check your SC) in the meantime...

**Comment by alexisgauba** [comment]
Absolutely! We’re currently talking to Etherscan to get them verified, were unfortunately having some issues when we were trying to verify :/ but they’ve started responding, so hopefully soon!

Best,
Alexis
