### ISSUE TITLE
Swaps query might be causing positions issues

### ISSUE THREAD

**Issue by alexisgauba** [opynfinance/squeeth-monorepo#168]
**Describe the bug**
- Folks who have manually minted + sold have reporting seeing incorrect short values 
- Someone who went long isn't able to see their position on the dashboard 

**To Reproduce**
1. Go short, manually rebalance (mint + sell more), close position 
2. Go long 

**Expected behavior**
Should show the accurate positions and positions should not disappear 

**Screenshots**
<img width="733" alt="Screen Shot 2022-02-15 at 12 26 26 AM" src="https://user-images.githubusercontent.com/13340486/154012915-4a8442af-fa2f-401b-97ec-a501836fb48d.png">
<img width="467" alt="Screen Shot 2022-02-15 at 12 27 58 AM" src="https://user-images.githubusercontent.com/13340486/154013162-0543a59c-8531-40cb-85e8-38d85c467f03.png">
<img width="453" alt="Screen Shot 2022-02-15 at 12 28 08 AM" src="https://user-images.githubusercontent.com/13340486/154013183-cce13e01-37ae-4a06-810d-ddaa998f6c29.png">

**Comment by EstherSeyi** [comment]
@yichiehliu I think this is the issue where it seems like swaps were not being loaded on time so even though I have a position it seems like I don't. I have a Long position in the image below.

<img width="1440" alt="Screenshot 2022-02-15 at 08 33 44" src="https://user-images.githubusercontent.com/40301524/154013988-83c39f74-6330-45ae-b080-97ae720f615b.png">

**Comment by alexisgauba** [comment]
There are a couple more folks having positions issues that seem related to swaps

**Situation 1**
<img width="800" alt="Screen Shot 2022-02-22 at 12 02 14 PM" src="https://user-images.githubusercontent.com/13340486/155220963-55f15d0f-d0d4-42df-8d3a-e18a67a5408b.png">
![Image from iOS (1)](https://user-images.githubusercontent.com/13340486/155221012-735850c3-cccd-4c31-a6e8-4afc80c63def.jpg)

Tested locally and got it show but looks like a graph error in the console 
<img width="1326" alt="Screen Shot 2022-02-22 at 1 00 27 PM" src="https://user-images.githubusercontent.com/13340486/155221062-d2ffec60-3d77-4a57-b770-12ee46b318d0.png">

**Situation 2**
![Image from iOS](https://user-images.githubusercontent.com/13340486/155221107-45f50cca-c221-4195-b06a-13bd12c3af8e.jpg)

Tested locally and can't see their position either. Getting a couple of different errors, some graph related some maybe related to LP NFT approval? (cc @KMKoushik) 

<img width="1318" alt="Screen Shot 2022-02-22 at 1 20 41 PM" src="https://user-images.githubusercontent.com/13340486/155221218-a4682b9b-94b9-4abe-8d85-fc33fec068d5.png">
<img width="1298" alt="Screen Shot 2022-02-22 at 1 20 14 PM" src="https://user-images.githubusercontent.com/13340486/155221224-88de7f94-6fd6-4c40-a911-4d85b34c024f.png">
