### ISSUE TITLE
Implement state management with jotai

### ISSUE THREAD

**Issue by alexisgauba** [opynfinance/squeeth-monorepo#176]
Based on @EstherSeyi spec 

@EstherSeyi pls comment with spec once it's complete

**Comment by alexisgauba** [comment]
Need to have metrics to measure difference as well. Crucial thing to measure is re-renders https://github.com/welldone-software/why-did-you-render

Cc @EstherSeyi @adam5909099

**Comment by KMKoushik** [comment]
Done
