### ISSUE TITLE
Use max debt amount for max to burn, not oSQTH Bal

### ISSUE THREAD

**Issue by alexisgauba** [opynfinance/squeeth-monorepo#183]
**Describe the bug**
Right now if you click "max" for burning oSQTH on "adjust debt", max will give your oSQTH Bal. Instead max, should give your oSQTH debt since that is the max you can burn 

**To Reproduce**
- Create a short position 
- Buy more oSQTH (from Uniswap) than you have debt 
- Go to vault manager and click "max" for burning oTokens

**Expected behavior**
Use max debt for max amount to burn. Similar to short/close do a check between the swaps calculated debt amount and the on chain amount, falling back to the on chain amount if the swaps calculated debt amount is different from the on chain amount

https://github.com/opynfinance/squeeth-monorepo/blob/18e786358c28bda26037a8175554a9101c71cd15/packages/frontend/src/components/Trade/Short/index.tsx#L600

**Screenshots**
<img width="686" alt="Screen Shot 2022-02-21 at 11 47 40 AM" src="https://user-images.githubusercontent.com/13340486/155011827-c8c4bfbd-f990-4d6f-b5e6-2e9037750323.png">

**Comment by KMKoushik** [comment]
Fix merged!
