### ISSUE TITLE
Long/Close didn't load a user's oSQTH balance

### ISSUE THREAD

**Issue by alexisgauba** [opynfinance/squeeth-monorepo#220]
**Describe the bug**
User went to long/close on the trade page to close their long squeeth position, but it didn't register their balance. They were concerned until they went to Uniswap, saw their balance, and closed out their position from there

**To Reproduce**

1. Open a long position buy buying squeeth from long/open 
2. Leave the page 
3. Go back to squeeth.com and try to close oSQTH position by selling from long/close on the trade page 

**Expected behavior**
Should load user's oSQTH balance letting them close from long/close

**Comment by yichiehliu** [comment]
It still happens to me sometimes, so reopened the issue
https://user-images.githubusercontent.com/26922518/165255039-6f77976a-59d1-4413-a185-7ec1a4308b14.mov
