### ISSUE TITLE
Position card not loading

### ISSUE THREAD

**Issue by alexisgauba** [opynfinance/squeeth-monorepo#249]
**Describe the bug**
Position card not loading position - seems to do it occasionally but after maybe 5+ minutes.
Vault has mint+sold via short helper as well as additional mint + sell in 2 steps via vault manager.
Can see position and vault on the positions tab.

**To Reproduce**

1. Open a position
2. Go to trade page and view position card

**Expected behavior**
Position card should load the position immediately 

**Screenshots**
<img width="441" alt="Screen Shot 2022-03-18 at 12 49 11 PM" src="https://user-images.githubusercontent.com/13340486/159098701-96fc5111-3e6d-46fe-850e-fd8f4e1baa53.png">

**Comment by adam5909099** [comment]
@KMKoushik FYI, I asked Andrew yesterday, and he told me that it's not reproducible on his side.
CC @alexisgauba

**Comment by KMKoushik** [comment]
I am closing this for now. We can re-open if needed
