### ISSUE TITLE
When select partially close on short side, even input a small amount of oSQTH to close, there will still be minimum collateral input error

### ISSUE THREAD

**Issue by yichiehliu** [opynfinance/squeeth-monorepo#276]
**Describe the bug**
Sometimes when select partially close on short side, and I want to close 0.001 amount of short oSQTH, which Im sure there will still have more than 6.9 collateral in the vault after this trade, but there will still be Minimum Collateral error in the input 

**To Reproduce**

1. Go to close short 
2. Click on partially close, CR at 200% by default
3. Enter a small amount of oSQTH to close

**Expected behavior**
Thought that as long as there is enough collateral and CR above 150%, users are able to close the short partially, there shouldn't be the error if users' inputs meet the condition 

**Screenshots**

**Additional context**

**Comment by EstherSeyi** [comment]
@yichiehliu is the expected behavior of this issue for the user to be able to close the position partially if the collateral ratio is greater than 150%? I'm a bit confused. Cc @KMKoushik

**Comment by yichiehliu** [comment]
And also with enough collateral in the vault
