### ISSUE TITLE
When select partially close for short position, it sometimes will jump to full close

### ISSUE THREAD

**Issue by yichiehliu** [opynfinance/squeeth-monorepo#279]
**Describe the bug**
When select partially close for short position, it sometimes will jump to full close
which cause tests to fail sometimes

**To Reproduce**

1. Go to Open short position
2. Click on short close tab
3. Select partial short close
4. Wait for couple of secs, it may jump to full close for no reason
5. It's a random bug, not reproducible every time

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by EstherSeyi** [comment]
@yichiehliu can you please give steps to reproduce this bug?

**Comment by yichiehliu** [comment]
@EstherSeyi Updated!

**Comment by EstherSeyi** [comment]
I was unable to recreate this. I followed the below steps a couple of times.
- Go to short close tab
- Select partial close.
- Wait for a few minutes

Cc @KMKoushik
