### ISSUE TITLE
User short oSQTH balances in the input box did not update to the latest user balance after partial short close

### ISSUE THREAD

**Issue by yichiehliu** [opynfinance/squeeth-monorepo#280]
**Describe the bug**
User short oSQTH balances in the input box did not update to the latest user balance after partial short close, but position card does

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="895" alt="image" src="https://user-images.githubusercontent.com/26922518/161067816-d3620053-e4d4-4952-9e57-beb9d03b0209.png">

**Additional context**

**Comment by yichiehliu** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/26922518/161200456-9e8d7b74-01ae-46b5-9ddd-d3f0dfa8fa18.png">

Also not updated on long side

**Comment by KMKoushik** [comment]
@adam5909099 Think this PR https://github.com/opynfinance/squeeth-monorepo/pull/356 will fix the issue
