### ISSUE TITLE
Short position card pnl keeps showing loading state

### ISSUE THREAD

**Issue by yichiehliu** [opynfinance/squeeth-monorepo#282]
**Describe the bug**
Short position card pnl keeps showing loading state

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="842" alt="image" src="https://user-images.githubusercontent.com/26922518/161087661-5b689c9e-c62f-4264-a4dd-20d9d37735f7.png">
**Additional context**

**Comment by akwritescode** [comment]
hey @adam5909099 assigning this to you as you are working on the P & L changes to add them back.
Once you add them back, ensure that this problem is not happening before closing this issue.

**Comment by akwritescode** [comment]
Closing this. As this will be handled in the new P & L rewrite that is being tracked at https://linear.app/opyn/project/position-and-pandl-9bb41f5486c5/ENG
