### ISSUE TITLE
LP rebalances that either trade or mint may not get the amount of oSQTH correct, can we fix?

### ISSUE THREAD

**Issue by aleone** [opynfinance/squeeth-monorepo#300]
Is there a way to ensure that the amount of oSQTH purchased (or sold) is the exact amount required, maybe by checking w uniswap nft manager some way?  Similar to [#299](https://github.com/opynfinance/squeeth-monorepo/issues/299), but making a new issue for the rebalance case.   Ideally we should be able to know the exact amount needed before we mint/buy/etc instead of using the f/e provided numbers and needing to burn/send back excess.

Issues basically anywhere we call checkExcess

**Comment by haythem96** [comment]
fixed
