### ISSUE TITLE
checkPartialLpClose is not needed in rebalanceWithouVault (as currently implemented)

### ISSUE THREAD

**Issue by aleone** [opynfinance/squeeth-monorepo#301]
This is unnecessary if this function only is used for full closes and new ranges (as the liquidity percentage above is hardcoded as 1e18)

**Comment by haythem96** [comment]
This should be fixed as the function renamed to `checkClosedLp()` to send back empty NFT https://github.com/opynfinance/squeeth-monorepo/blob/main/packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol#L213

**Comment by aleone** [comment]
fixed
