### ISSUE TITLE
Return newly created vault ids

### ISSUE THREAD

**Issue by aleone** [opynfinance/squeeth-monorepo#328]
We should probably return newly created vault ids in controller helper in the external called functions, this might be needed / helpful

**Comment by haythem96** [comment]
Do u think this helper will be called by third party contracts ?

**Comment by aleone** [comment]
I'm not sure, it seems like an easy interface for vaults to use for integrating with liquidity for LPing or selling/buying oSQTH

**Comment by aleone** [comment]
@haythem96 add dis

**Comment by haythem96** [comment]
After looking into this, I see some logic that mint the new vault is in the callback function, like the `flashswapSellLongWMint()`, so to return the new vaultId, it should be returned to the parent function through `_exactInFlashSwap()` which I don't think it is good.

I'm more toward not returning the new vaultId now as any other external contract know the passed vaultId in the params, so if it is == 0 then they just need to get the vault counter before their tx.

wyt ?

**Comment by aleone** [comment]
thats ok with me

**Comment by haythem96** [comment]
Closing this as we agree to not return created vault ID
