### ISSUE TITLE
lpWPowerPerpPool sometimes is used where weth is wrapped before calling othertimes requries _params.ethAmount

### ISSUE THREAD

**Issue by aleone** [opynfinance/squeeth-monorepo#334]
- in ```rebalanceWithoutVault``` any eth attached is wrapped to weth, calling with ```_params.ethAmount``` > 0 will fail
- in ```rebalanceVaultNft``` can have a mix of weth and eth (weth when reducing liquidity, eth from msg.value, removing collateral). correctly specifying the ethAmount seems tricky and its possible that we will have a mix of weth and eth that will need to be tracked and correctly passed (ethAmount is the msg.value and amount0Desired/amount1Desired would be weth and eth combined (can it use a mix?) )

**Comment by alpinechicken** [comment]
no `_params.ethAmount` for `rebalanceWitoutVault`.  Runs for me with   `await controllerHelper.connect(depositor).rebalanceWithoutVault(params, {value: collateralAmount});`

**Comment by aleone** [comment]
1st one: once in rebalanceWithoutVault any eth attached is wrapped to weth, calling with _params.ethAmount > 0 will fail is fixed, add in an explicit test that should fail @haythem96 to fix

2nd one: @haythem96 to look at, and maybe implement standard way to unwrap only for deposits of ETH/eth attach for msg.value passes
