### ISSUE TITLE
Github bytecode doesn't match mainnet bytecode

### ISSUE THREAD

**Issue by hitsuzen-eth** [opynfinance/squeeth-monorepo#34]
Github bytecode doesn't match mainnet bytecode !
![image](https://user-images.githubusercontent.com/97344384/149151597-739e171e-478f-4896-8097-28fe944dc9ab.png)

**Comment by antoncoding** [comment]
it's because we changed a constants during deployment (the 6.9 eth collateral) and change it back and commit on github, just so it doesn't mess up all the tests. (all our tests were based on a min collateral of 0.5 eth).

you can try changing that constant and see if it still give you this error!

**Comment by antoncoding** [comment]
Closing this as contract is now verified!
