### ISSUE TITLE
Max button in input box is not working 

### ISSUE THREAD

**Issue by yichiehliu** [opynfinance/squeeth-monorepo#364]
**Describe the bug**
You have some long oSQTH balance, and then click on MAX in input box, the ETH input will remain zero

**To Reproduce**

1. Go to open long
2. Click on close long tab
3. Click on max

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/26922518/164428455-8efc6b6d-bced-4bf3-91ba-baceafea32a8.mov

**Additional context**

**Comment by EstherSeyi** [comment]
I couldn't recreate this issue. Seems to be fixed somehow.
