### ISSUE TITLE
Should never show $0 for pnl of an open position

### ISSUE THREAD

**Issue by yichiehliu** [opynfinance/squeeth-monorepo#376]
**Describe the bug**
It should never show $0 pnl value for an open position on either position card or position page

**To Reproduce**

1. Go to open position
2. Go to position page or trade page
3. See PnL value in position card

**Expected behavior**
Not to show 0

**Screenshots**

**Additional context**

**Comment by akwritescode** [comment]
Closing this. As this will be handled in the new P & L rewrite that is being tracked at https://linear.app/opyn/project/position-and-pandl-9bb41f5486c5/ENG
