### ISSUE TITLE
On Full Close, it defaults to users max oSQTH amount and shows an insufficient ETH Balance error 

### ISSUE THREAD

**Issue by yichiehliu** [opynfinance/squeeth-monorepo#379]
**Describe the bug**
Should take users' ETH amount into account when calculate max oSQTH amount user can input

**To Reproduce**

1. Go to open short position
2. Click on close
3. See error

**Expected behavior**
Not to have insufficient ETH Balance error on short full close

**Screenshots**

**Additional context**

**Comment by yichiehliu** [comment]
Close this issue cuz we should enter the actual max amount of osqth for users, if their eth amount is not enough, they should find sufficient amount of eth on their own or close partially with less osqth amount.

**Comment by KMKoushik** [comment]
This is how all other FEs do it. That's the reason behind closing this!
