### ISSUE TITLE
Vault Information not loading on Positions  after a successful shorting action performed on ROPSTEN

### ISSUE THREAD

**Issue by DemolaJames** [opynfinance/squeeth-monorepo#392]
**Describe the bug**
After taking a short position, user clicks on positions but vault information is not loaded  

**To Reproduce**

1. On (https://squeeth.opyn.co/) Go to on trade and open a short position 
2. When transaction is successful, Click on positions to view updated information 
3. Scroll down to 'Vault' section 
4. See error: error is that the vault information is not shown 

**Expected behavior**
After successfully opening a short position, i should see the vault information when i click on positions and not have to reload the page. 

**Additional context**

**Comment by adam5909099** [comment]
I've tried several times and confirmed it's fixed though it takes 3 or 4 seconds to load the position card and vault data.
