### ISSUE TITLE
For an existing vault w flashloanWMintDepositNft, we withdraw collat at end so a user cant use vault collateral for LPing 

### ISSUE THREAD

**Issue by aleone** [opynfinance/squeeth-monorepo#399]
I think withdrawing the collateral at the start of the transaction is a better pattern as a user may want to use their collateral for LPing.  A use case would be someone has a 300 CR short with a bunch of ETH collateral and want to mint + LP against the vault using some of the excess vault collateral for it. Most of vault collateral can be used if the LP token is deposited as collateral.  It may be impossible to use the ETH as collateral unless we change the pattern of withdrawing.

**Comment by haythem96** [comment]
Wouldn't this withdraw fail if the vault do not have the LP NFT deposited ?

**Comment by aleone** [comment]
They can just take a larger flashloan if that would be the case, all that will matter is if at the end of the tx the user vault is collateralized correctly.

**Comment by haythem96** [comment]
So no change needed here, right ? 
If user want to use vault collateral to LP, just flashloan that amount, LP, withdraw it later from vault and repay.
