### ISSUE TITLE
RebalanceVaultNft actions don't share state and can lead to suboptimal user results

### ISSUE THREAD

**Issue by aleone** [opynfinance/squeeth-monorepo#411]
Related to #383 , there are some use cases where users may often have unexpected oSQTH that is returned to them or too much is minted.

Some common use cases that aren't supported:
- burn the exact amount of oSQTH removed from a decreaseLiquidity call

**Comment by haythem96** [comment]
Will add a burnExactRemoved flag, and if set to true burn all contract balance, wyt ?

**Comment by haythem96** [comment]
Fixed
