### ISSUE TITLE
mintAndLP returns vaultId=0

### ISSUE THREAD

**Issue by alpinechicken** [opynfinance/squeeth-monorepo#414]
**Describe the bug**
mintAndLP in ControllerHelperUtil returns vaultId=0 if there is no mint. This makes mintNewLP in ControllerHelper fail because it tries to deposit the token to vault 0. 

**To Reproduce**

Call rebalanceVaultNft with mintNewLP when there is already enough wPowerPerp

**Expected behavior**
Should return existing vaultId 

**Screenshots**

**Additional context**
I think setting default vault fixes

`uint256 _vaultId = _mintAndLpParams.vaultId;`

 Broken test here 
https://github.com/opynfinance/squeeth-monorepo/pull/406/commits/4754a81d641d5ad1d2596911bfe36ecee6bfddc2

**Comment by haythem96** [comment]
Fixed
