### ISSUE TITLE
Naming improvements

### ISSUE THREAD

**Issue by aleone** [opynfinance/squeeth-monorepo#473]
Some suggestions/examples where I think could be improved:

mintIntoVault -> mintDepositInVault (basically including the deposit in name)
withdrawFromVault -> burnWithdrawInVault (basically including the burn in name)
batchMintLp -> mintLp (batch used here but not below)
flashloanWMintDepositNft -> flashloanMintLpDepositNft
rebalanceWithoutVault -> rebalanceLpWithoutVault
rebalanceVaultNft -> rebalanceLpInVault

**Comment by alpinechicken** [comment]
+ these from other issue 

Naming of some of the recent params structs inconsistent. @haythem96 mentioned in PR iirc. @aleone wdyt?

Suggestions for consistent names:
DepositIntoVault -> DepositIntoVaultParams
withdrawFromVault -> WithdrawFromVaultParams
GeneralSwap -> GeneralSwapParams
closeUniLpParams -> CloseUniLpParams
ReduceLiquidityAndSell -> ReduceLiquidityAndSellParams
RebalanceWithoutVault -> RebalanceWithoutVaultParams
LpWPowerPerpPool -> LpWPowerPerpPoolParams
IncreaseLpLiquidityParam -> IncreaseLpLiquidityParams

**Comment by haythem96** [comment]
Will rename `batchMintLp` to `wMintLp` instead of `mintLp`
