### ISSUE TITLE
Positions don't reload on the positions tab or vault manager 

### ISSUE THREAD

**Issue by alexisgauba** [opynfinance/squeeth-monorepo#62]
**Describe the bug**
The positions card and short input are now showing the right value for positions, but it takes those about three reloads to show the right value. The positions tab and vault manager _don't_ reload, so positions doesn't show up at all and vault manager gets stuck showing the wrong value. This is potentially because the LP loading is not taken into account? 

<img width="1374" alt="Screen Shot 2022-01-15 at 6 08 04 PM" src="https://user-images.githubusercontent.com/13340486/149645615-cbb25278-bb84-48b4-ac61-711c09336517.png">
<img width="1389" alt="Screen Shot 2022-01-15 at 6 07 52 PM" src="https://user-images.githubusercontent.com/13340486/149645617-973b64ce-4dff-4d5e-ab2c-9a47952e51e1.png">
<img width="1189" alt="Screen Shot 2022-01-15 at 6 07 15 PM" src="https://user-images.githubusercontent.com/13340486/149645618-f97b6824-9c25-4f09-a88c-3e109faaac16.png">

**To Reproduce**
1. Mint some oSQTH 
2. Add liquidity to LP
3. Go short 
3. Remove LP liquidity 
4. Check positions card, short / close, positions tab, and vault manager

**Expected behavior**
- Positions tab should show a short position with the same value as positions card 
- Vault manager should show the same value as positions card for short debt, and should actually show the minted debt (right now shows 0)
- Adjust debt max to burn should show the oSqueethBal, not 0

**Comment by yichiehliu** [comment]
Also fixing on collateral ratio indifference on vault manager and position page
![image](https://user-images.githubusercontent.com/26922518/150107758-757bca9c-f5a7-470b-927a-7b6af3910487.png)
![image](https://user-images.githubusercontent.com/26922518/150107872-587beb9c-76f9-4dfc-86c0-f6c638304eff.png)
