### ISSUE TITLE
Use the correct ETH collateral amount for taking ETH collateral into account for short PnL

### ISSUE THREAD

**Issue by alexisgauba** [opynfinance/squeeth-monorepo#85]
**Describe the bug**
#47 updated the formula for PnL, but uses the wrong data for calculating the ETH collateral portion 
- It is using ETH amount from the Uniswap swap, _but_ that is _not_ the collateral amount, that is the amount the user earns from selling their oSQTH on Uniswap

**To Reproduce**

1. Create a short position 
2. Check the unrealized PnL 

**Expected behavior**
- It _should_ use the amount of collateral the user put down to mint their oSQTH. 
- Additionally, if a user partially closed their position, it should take that into account as well 

Unrealized Formula: `((amt of ETH earned from selling oSQTH) - (amt of ETH to pay to buy oSQTH back) * ETH price) + ((initialEthDeposited - any collateral removed)* (ethPriceNow - ethPriceAtDeposit))
`

As EJ called out below, need to update realized as well

**Comment by yichiehliu** [comment]
Do we also update the pnl of any collateral removed to realized pnl?

**Comment by alexisgauba** [comment]
> Do we also need to update the pnl of any collateral removed to realized pnl?

yep!
